---
title: "Adaptations to Pollination"
author: "J. Hillert"
date: "`r Sys.Date()`"
output:
  bookdown::word_document2:
    number_sections: false
    toc: no
    always_allow_html: true

bibliography:
- aRticles.bib

csl: ecology.csl
---


```{r setup, include=FALSE}

knitr::opts_chunk$set(message=FALSE,
                      echo=FALSE,
                      warning=FALSE)

library(papaja)
library(tidyverse)


papaja::r_refs(file = "paper1.bib")

options(knitr.kable.NA = "")


```

#
  Climate change is an unpredictable phenomenon and how mutualisms will be affected is poorly understood. Efforts to gain a deeper knowledge of how mutualisms could change examined here are the introduction of non-native species whose range could be affected by climate change and how climate change could cause a disturbance significant enough to affect ecosystem stability in a network of mutualists. The introduction of non-native threatened species is an example of assisted migration but meets pitfalls when specialized mutualists' pollinator is absent. In the highly dynamic islands of the Galapagos, species must resort to omnivory to supplement their diet and act as double mutualists, but in the deeply woven network disturbance is bound to affect ecosystem stability. These situations are described below and their implications are discussed at the afterward. 

#
  The Galapagos Islands are an incredible example of co-evolution and co-adaptation under intense selective pressures from climate to nutrition. Mutualisms are essential in this type of environment and in some cases, some mutualists can act as double- even triple-mutualists by reusing elements of plant material. This herbivory in birds is a necessary adaptation to oceanic island life, species including birds, lizards, and some reptiles, must resort to omnivory to widen their food niche and achieve adequate nutrition. In this way @Olesen.2018 found a network of mutualisms between 108 plants and 21 bird species, of which, 12% and 48% of these acted as double mutualists, respectively. They found that the double mutualist birds rely on single mutualist plants for food at multiple life stages and vice versa with the single mutualist relying on the double mutualist for pollination service and for seed dispersal. This behavior in the double mutualist birds creates an unstable feedback loop when the floral resources are consumed. For example, the foraging of nectar provides food for the bird and aides the plant in pollination, later the plant produces more fruit for the bird to forage therefore increasing seed dispersal. This positive feedback loop is unstable because perturbations in the network will easily propagate throughout. The authors found that this disturbance would be more evident in bird biodiversity as they are more reliant on the pollination-seed dispersal double mutualism. This makes double mutualisms a risky albeit necessary method of survival in island habitats where disturbance would be greater immediate impact on the double mutualist birds and less impact or delayed impact on the single mutualist plants. Given the unpredictability of weather patterns associated with climate change, an intense disturbance could severely alter this network and affecting ecosystem stability. Luckily, the authors propose a mitigation effort of the introduction of an analogous species to fill the gap. Resistance to this measure could come from debates over introducing an invasive species.

#
  Another example that has the potential to be affected by climate change draws from the introduction of species to similar environments where it was previously absent. In this instance, the flower Bird of Paradise, *Strelitzia reginae*, an ornamental flower used in tropical gardens in warm-tempered regions similar to S. Africa, such as California and Florida. It is normally pollinated by the endemic South African Cape Weaver, *Ploceus capensis*, but this becomes a problem when the pollinator is not present where the flower has been introduced. Bird of Paradise is highly specialized for *P. capensis* and propagation outside of S. Africa is generally accomplished from seeds which could then be hand pollinated. In a study done by @Hoffmann.2011 looking at ornithophily of *S. reginae* in its introduced range, they found that various sparrows and particularly the Common Yellowthroat Warbler, *Geothlypis trichas*, foraging the nectar from the flower or at least visiting the flower. The activity of *G. trichas* is similar to that of *P. capensis*, in that, both visit the flowers in the same manner. However the warbler is drawn to the ants feeding from the flowers rather than the nectar itself. Furthermore, the warbler will supplement its diet with nectar as this species is an opportunistic feeder and will visit multiple flowers. This behavior pollinates *S. reginae* akin to the endemic pollinator indicating that the warbler has been co-opted for pollination. This conspiracy between *S. reginae* and *G. trichas* is a step towards overcoming establishment barrier in introduced regions by inciting a mutualism. Whether this is a new forming mutualism or the first time observing the mutualism, is unclear, as are the implications. On the positive end, there is an argument for conservation of expanding its range in the face of climate change. While on the negative end, there is potential for this plant to become invasive, however the initial hurdle will still be establishment. Still, it is interesting to witness a potentially new mutualism form which could further our knowledge about mutualisms and about adaptations in the face of climate change. 

#
  Climate change is likely to disrupt the stability of the double mutualism pollination-seed dispersal network in a disproportionate way at the expense of avian species. If the Galapagos network is disrupted, an analogous species could be introduced to mitigate the loss of the pollinator-seed dispersing double mutualist. This also has the potential to further disrupt the stability through the introduction of an invasive species. In the other example, native warm-tempered habitats may become fragmented and establishment in similar regions may be necessary for conservation. When introducing a non-native species into an analogous habitat a barrier it could face is the absence of its specialized mutualist, this can be overcome by co-opting local generalists that are opportunistic and omnivorous feeders by nature. This would then lead to adaptation away from specialized pollination and could be an example of the formation of a new mutualism. In either case, mitigation efforts have been proposed or observed that could lead to persistence of species involved in these mutualisms in the face of climate change.  

# References
