---
title: "Phenolic Compunds in Green Tea and Green Tea Kombucha"
author: "J. Hillert"
date: "`r Sys.Date()`"
output:
  bookdown::word_document2:
    number_sections: false
    toc: no
    always_allow_html: true

bibliography:
- aRticles.bib

csl: ecology.csl
---


```{r setup, include=FALSE}

knitr::opts_chunk$set(message=FALSE,
                      echo=FALSE,
                      warning=FALSE)

library(papaja)
library(tidyverse)


papaja::r_refs(file = "paper.bib")

options(knitr.kable.NA = "")


```

### Introduction

Green tea, white tea, and black tea each originate from the *Camellia sinensis* plant which is native to the tropical and temperate regions of Asia, Africa, and South America [@Gopa.2016]. Small leaves and leaf buds are unfermented and used to make green tea, while white tea is composed of semi-fermented buds, and black tea is composed of fully fermented old leaves [@NCSU]. Tea is a globally consumed beverage second only to water and the drink is praised for its numerous health benefits. Briefly, tea has anti-carcinogenic, anti-angiogenic, anti-mutagenic, anti-inflammatory, anti-bacterial, hypocholesterolemic, anti-diabetic, and shows protection against Parkinson's and Alzheimer's disease [@Chac.2010; @Gopa.2016]. These and many other health benefits are mainly attributed to green tea polyphenols, less so to flavonols and gallic acid derivatives, vitamins, minerals, enzymes, and others [@Gopa.2016]. Another health drink rising in popularity is Kombucha - which is a fermented beverage resulting from a symbiotic culture of bacteria and yeast (SCOBY) in a sweetened tea solution for about two weeks. The flavor profile shifts from sweet to tart to sour with increased fermentation time, temperature and SCOBY microbe composition. The total phenolic content of kombucha made from green or black tea is over three times greater than regular green or black tea [@Zhou.2022]. Green tea and kombuchas are popular for their numerous health benefits and fermentation with a SCOBY enhances these benefits and is suggested by @Jaku.2020 a diet including kombucha can help support the body's antioxidative response, especially for those exposed to mental and physical stress.

### Polyphenols of Green Tea and Green Tea Kombucha

The components of green tea (GT) that gives the drink its health benefits comes from polyphenols, flavanols, and gallic acid derivatives [@Gopa.2016]. Important compounds among the polyphenols includes alkaloids, carbohydrates, catechins, enzymes, free amino acids, minerals and vitamins. The health benefits are most particularly associated with the catechins which comprise 25% - 35% of GT dry weight. The two most effective antioxidant compounds are EGCG and ECG. EGCG is also the most active and abundant - one cup of GT could have 100-200 mg EGCG. @Gopa.2016 found that EGCG can help prevent dental cavities, inhibition of multiple drug resistant Staphylococcus aureus, and inhibition of HIV infection. 

Fermentation is the metabolic breakdown of carbohydrates producing chemical changes in the organic substances via the action of enzymes associated with the SCOBY [@Noma]. Fermentation with a SCOBY - symbiotic culture of bacteria and yeast - can increase the total polyphenolic  concentration over five-fold when compared to GT without SCOBY fermentation [@Zhou.2022]. Likewise, antioxidant ability increased over three-fold in green tea kombucha (GTK) with tea residue vs GTK or GT. The health benefits associated with GT are related to catechin consumption and absorption, but is limited by absorption. Fermentation increases the concentration of phenolic compounds and increases the antioxidant potential. @Card.2020 identified 127 phenolic compounds associated with GTK with 70% of compounds in the flavonoid class (i.e. catechins), and the last 30% split between phenolic acids and other polyphenols. Among these compounds are also vitamins B, E, and K, fluoride, potassium, and manganese ions, amino acids, and a variety of organic acids - acetic, citric, gluconic, glucuronic, lactic, malic, malonic, and succinic [@Jaku.2020]. Tea type has a significant effect on antioxidant potential, pH, acidity, alcohol content, and sugar content, with greater effects in GTK vs black, white, or red tea derived kombuchas. It is likely that tea quality also has an effect on these properties, potentially increasing antioxidant activity and concentration even further. 

### Health Benefits of Green Tea and Green Tea Kombucha

Green tea (GT) has antioxidative, anti-carcinogenic, anti-diabetic, anti-hypertensive, anti-inflammatory, anti-mutagenic, anti-proliferative, anti-thrombogenic, among many other properties [@Chac.2010; @Gopa.2016; @Vela.2008] giving the drink its status as a health drink. @Hein.2011 have shown that a flavanoid-rich diet can help prevent certain cancers and cardiovascular diseases, specifically related to UV-induced damage following sun exposure in women. Polyphenols in GT were shown to protect against many damaging effects of UV radiation, such as sunburn response, immunosuppression, and photo-aging. Flavonoids - epigallocatechingallate (EGCG), epicatechingallate (ECG), and epicatechin (EC) - are easily absorbable and bioavailable upon ingestion with the latter two primarily absorbed in the small intestine and 20-50% recovered in urine. They show that consumption of GT with ~1400 mg of catechins per serving can reduce UV-induced erythema by 16% at 6 weeks and 25% at 12 weeks. Prolonged consumption of GT polyphenols and carotenoids at 6 months decreases overall solar damage and at 12 months reduces UV-induced erythema telangiectasis. This research shows that the body readily absorbs polyphenolic compounds and is able to use and recycle them to some extant before excretion. 

Green tea extract (GTE), a concentrated form of GT mainly consisting of antioxidants, shows effects on working memory modulation by increasing neural connectivity [@Schm.2014]. EGCG increases connectivity from the right superior parietal lobule to the middle frontal gyrus and connectivity is positively correlated with task performance. Protection of cognitive function by EGCG is accomplished through antioxidation, iron-chelation, and modulation of cell signalling and cell survival pathways. These actions were shown to reduce oxidative stress induced by neurotoxicity, promote neural plasticity in mice, decrease beta-amyloid levels and plaques in Alzheimer's mice, and facilitate Calcium-dependent glutamate release in rats. Mice and rats are biologically analogous to humans and the effects shown can be translated to humans. These effects shown in GTE by @Schm.2014 indicate possible effects on neurodegenerative diseases such as Alzheimer's and Parkinson's in humans. 

Obesity is a global problem and a catechin-rich diet has been shown to decrease intra-abdominal fat (IAF) in an overweight population [@Wang.2010]. They show that regular consumption of catechin-rich GT for greater than 90 days led to significant responses in body weight, waist circumference, and the most consistent effect in IAF. Catechin-rich diets have been shown to increase lipolysis during moderate-intensity exercise and decrease IAF [@Vena.2008; @Wang.2010]. GTE was shown to inhibit catechol 0-methyltransferase(5,6) and increase fat oxidation by 17% through lipolysis. @Vena.2008 show that GTE effects are not limited to fat oxidation. In men, GTE consumption can increase insulin sensitivity by 13% and improve glycemic control, thus reducing the risk of type II diabetes. 

Several studies have found a positive correlation between GT consumption and cardiovascular health. In a review by @Vela.2008, they found evidence that GT catechins improve blood lipid profiles, regulate vascular tone, prevent vascular inflammation, inhibit vascular smooth muscle proliferation, and inhibit thrombogenesis. In this review they found that plasma catechin levels were 0.2-2%, indicating that bioavailability of catechins is lower than amount absorbed. Despite this limitation in GT, the authors confirm the health benefits in literature with emphasis on cardiovascular health. They show that catechins positively affect plasma lipid profile and vascular function and inhibitory effects on oxidation, vascular inflammation, atherogenesis, and thrombogenesis. GT catechins antioxidant activity scavenges free radicals, chelates transition-metal ions, inhibit pro-oxidant enzymes in favor of antioxidant enzymes. 

Fermentation of tea with a SCOBY into kombucha provides the drink the health benefits associated with GT and increases antioxidant activity and concentration. This potentially provides as of yet unstudied health benefits. Kombucha is a popular beverage for its role as a functional food that provides vitamins, minerals, organic acids, polyphenols, and enzymes. A commonly touted health benefit of kombucha comes from the microflora of the SCOBY that provide the drink its probiotic effect. Among the *in vitro* and *in vivo* studies reviewed by @Kapp.2019, they do confirm kombuchas potential to have antimicrobial effects, liver and gastrointestinal responses, stimulate the immune system, detoxify the liver, antioxidant activity, anti-tumor activity, and could aid the body against diabetes, cardiovascular disease, and neurodegenerative diseases. Further research about the health benefits of kombucha are needed, especially in human subjects.

### Kombucha Considerations

While fermentation is an effective method to provide flavors and vital nutrients [@Hsie.2021], kombucha is limited by tea type, fermentation time and temperature, and SCOBY microfloral composition. Mentioned previously and evident in many of the studies discussed here, tea type has an effect on the phenolic profile and antioxidant potential of kombucha. Depending on which quantifying method is used - FRAP assay, DPPH assay, total phenolic content (TPC), or total flavonoid content (TFC) - kombucha tend to follow a trend of greatest values in green tea or pu'er tea, followed by red, white, and black teas [@Jaku.2020; @Hsie.2021]. Fermentation time also has a significant effect on TPC and TFC, fermentation time increases these values were increased [@Hsie.2021]. This effect generally lasts around ten days before the increase plateaus and some catechin degradation occurs [@Jaya.2007], however it is generally less in GTK versus kombucha derived from red, black, or white. @Hsie.2021 noticed a decrease in antioxidant potential following the 8th day of fermentation in all tested kombucha. These changes associated with fermentation time are dependent on temperature during fermentation. Lower temperatures decrease mircofloral activity slowing the fermentation process, while higher temperatures increase microfloral activity, hasten the fermentation process, and invite the opportunity of infection from harmful bacteria [@Noma]. Among the microfloral associate with the kombucha SCOBY, different species are active at different periods of fermentation. Beginning with yeast activity to degrade the sugars into alcohol by *Saccharomyces*, *Brettanomyces*, or *Zygosaccharomyces* species. 


Yeasts [@Kurt.2001; @Teoh.2004]

### Future research

GT v GTK v PGT v PGTK

As noted by @Hein.2011, GT catechins have a range of effects similar to that of cocoa polyphenols, an addition of cocoa to kombucha during the secondary fermentation could cause a synergistic effect with GT polyphenols. 












\newpage

# References


















